"""
Coach routes — message, history, proactive insights.
Uses Claude API (claude-sonnet-4-20250514) for AI responses.
No mock/sandbox fallbacks — requires ANTHROPIC_API_KEY.
"""

import os
from datetime import datetime
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional, List
import anthropic
from prompts import check_guardrail, build_system_prompt, EXPERT_REDIRECT
from context_builder import build_transaction_summary, build_goals_summary

router = APIRouter()

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
if not ANTHROPIC_API_KEY:
    raise RuntimeError("FATAL: ANTHROPIC_API_KEY must be set in .env")

claude_client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

# Per-user conversation history (in production: store in DB)
_conversations: dict[str, list] = {}

# Rate limit: 20 messages per user per day
_rate_limits: dict[str, dict] = {}
MAX_MESSAGES_PER_DAY = 20


class MessageRequest(BaseModel):
    message: str
    language: Optional[str] = "hi"
    user_id: Optional[str] = "default"


def _check_rate_limit(user_id: str) -> bool:
    today = datetime.now().strftime("%Y-%m-%d")
    if user_id not in _rate_limits or _rate_limits[user_id].get("date") != today:
        _rate_limits[user_id] = {"date": today, "count": 0}
    return _rate_limits[user_id]["count"] < MAX_MESSAGES_PER_DAY


def _increment_rate_limit(user_id: str):
    today = datetime.now().strftime("%Y-%m-%d")
    if user_id not in _rate_limits or _rate_limits[user_id].get("date") != today:
        _rate_limits[user_id] = {"date": today, "count": 0}
    _rate_limits[user_id]["count"] += 1


@router.post("/message")
async def send_message(body: MessageRequest):
    """Send a message to the AI Coach. Uses real Claude API."""
    user_id = body.user_id or "default"

    # Rate limit check
    if not _check_rate_limit(user_id):
        return {
            "success": False,
            "error": f"Daily limit of {MAX_MESSAGES_PER_DAY} messages reached. Try again tomorrow.",
        }

    # Check investment advice guardrail
    if check_guardrail(body.message):
        redirect = EXPERT_REDIRECT.get(body.language, EXPERT_REDIRECT["en"])
        return {
            "success": True,
            "data": {
                "response": redirect,
                "guardrail_triggered": True,
            },
        }

    # Build context from user data
    # In production: fetch real transactions from DB via user_id
    txn_summary = build_transaction_summary([])
    goals_summary = build_goals_summary([])
    system_prompt = build_system_prompt(
        language=body.language or "hi",
        transaction_summary=txn_summary,
        mini_score=0,
        goals=goals_summary,
    )

    # Build conversation history
    if user_id not in _conversations:
        _conversations[user_id] = []

    _conversations[user_id].append({"role": "user", "content": body.message})

    # Keep only last 10 messages to stay under 4000 token budget
    messages = _conversations[user_id][-10:]

    try:
        response = claude_client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=120,
            system=system_prompt,
            messages=messages,
        )
        reply = response.content[0].text

        # Store assistant response in history
        _conversations[user_id].append({"role": "assistant", "content": reply})
        _increment_rate_limit(user_id)

        return {
            "success": True,
            "data": {
                "response": reply,
                "guardrail_triggered": False,
                "messages_remaining": MAX_MESSAGES_PER_DAY - _rate_limits.get(user_id, {}).get("count", 0),
            },
        }
    except anthropic.AuthenticationError:
        raise HTTPException(status_code=500, detail="Invalid Anthropic API key")
    except anthropic.RateLimitError:
        raise HTTPException(status_code=429, detail="Claude API rate limit exceeded. Try again shortly.")
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Claude API error: {str(e)}")


@router.get("/insights")
async def proactive_insights(language: str = "hi"):
    """
    Get proactive insights generated by Claude.
    In production: pre-generated as a batch job 3x/week.
    """
    system = f"You are Mini's AI Savings Coach. Generate 3 short, specific financial insights in {language}. Each insight should mention a specific amount. Use emojis. Keep each under 100 characters."

    try:
        response = claude_client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=300,
            system=system,
            messages=[{"role": "user", "content": f"Generate 3 proactive savings insights in {'Hindi' if language == 'hi' else 'Tamil' if language == 'ta' else 'Telugu' if language == 'te' else 'English'} for an Indian user."}],
        )
        raw = response.content[0].text

        # Split into individual insights
        insights = [line.strip().lstrip("0123456789.-) ") for line in raw.strip().split("\n") if line.strip() and len(line.strip()) > 10][:3]

        return {"success": True, "data": {"insights": insights, "language": language}}
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Failed to generate insights: {str(e)}")


@router.get("/history")
async def conversation_history(user_id: str = "default"):
    """Get conversation history for a user."""
    history = _conversations.get(user_id, [])
    return {
        "success": True,
        "data": [
            {**msg, "timestamp": datetime.now().isoformat()}
            for msg in history[-20:]
        ],
    }
